apiVersion: v1
kind: Namespace
metadata:
  name: axion
  labels:
    name: axion
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
